### ISSUE TITLE
depthmapX for Linux

### ISSUE THREAD

**Issue by shaief** [varoudis/depthmapX#15]
Dear Tasos,
Thank you for creating depthmapX. It's a very interesting software.

In the spacesyntax website it says that it is possible to use depthmapX on Linux. I didn't find this option nor instructions for compiling it on Linux. Is it possible to use it on Linux  and what are the dependencies?

**Comment by martyclark** [comment]
Hi Tasos,

I'm really struggling to install this in Ubuntu 14.04. Have you got any simple instructions for install the qt program?!

Thanks

Martyn

**Comment by varoudis** [comment]
Please google for a ubuntu guide to install qt creator and qt4 (remember its 4 NOT 5!)
Each Linux installation is different and NOT intended for beginners.

After installing these, compile is just a click.

Tasos

**Comment by martyclark** [comment]
Hi Tasos,

OK I've managed to compile and run depthmapX. I know this is a little off topic, but I'm actually trying to use the Space Syntax Toolkit plugin for QGIS. When I hit the 'calculate' button from the Graph Analysis plugin, it tells me to 'make sure depthmapX is running' - it is running, but I still get this error. Any ideas?

**Comment by varoudis** [comment]
It is not available for Linux at the moment. Use Windows or Mac.
Tasos

**Comment by martyclark** [comment]
Do you mean the plugin 'doesn't work' on Linux at the moment?

**Comment by varoudis** [comment]
depthmapXnet not working on linux, only depthmapX works.
Also, the plugin combined with dXnet was never tested on linux.

Its a future plan.

Tasos

**Comment by simogeo** [comment]
Hi all,

Something new regarding Linux implementation ? thanks

**Comment by pshavr** [comment]
hi is there any tutorial on installation?

**Comment by mcginnly** [comment]
> _Please google for a ubuntu guide to install qt creator and qt4 (remember its **4 NOT 5**!)_

just wondering if this is still the case?
(struggling to compile in qtcreator because e.g. generalpage.cpp line 17 refers to QtWidgets (QT5) rather than QtGui (QT4))

**Comment by varoudis** [comment]
Hi,
The latest is based on Qt5.
My original post was from 2015.
Tasos
