### ISSUE TITLE
depthmapx for windows 8

### ISSUE THREAD

**Issue by moosethofa** [varoudis/depthmapX#21]
Dear Tasos,
Thank you for creating depthmapX. It's a very interesting software.

but can u tell me, how to run depthmapx with qt creator in win 8...? i have some trouble with kits and the compile on build and run option...
it was the first time for using this software..

i hope u can tell me..
thank's

**Comment by varoudis** [comment]
Do you want to RUN depthmapX fro your work or develop and hack the code?

to run it, you DONT need qt-creator! Just the executable.

Tasos

**Comment by moosethofa** [comment]
thank's sir....
