### ISSUE TITLE
Cannot save or open .graph files on Windows 10

### ISSUE THREAD

**Issue by MartinPetkov** [varoudis/depthmapX#24]
I am trying to use this program on Windows 10, and it is unable to save or open .graph files. This means I fundamentally can't use the program. Please fix this immediately.

**Comment by Yuyujin** [comment]
I can't open .graph files. OS is Windows 7 Ultimate.

Used the .28 to .50 versions.

**Comment by varoudis** [comment]
I need to know a lot of things about your local setup, windows security settings, language settings etc.

The problems as usually related with windows security settings (fake activations? etc) and languages other than English.

**Comment by rtsaboya** [comment]
There seems to be an issue with paths with accents and other special characters. I have the same issue and was able to save to simple folders, like "c:/temp".

**Comment by varoudis** [comment]
yes its a known issue with other languages (in Windows).
http://stackoverflow.com/questions/23888263/russian-or-non-latin-filename-load-qt-windows
