### ISSUE TITLE
How to calculate WEIGHTED Step Depth?

### ISSUE THREAD

**Issue by lindaplzhou** [varoudis/depthmapX#27]
Hi All,

I am working on a segment map (convert from axial map) analysis for a course paper.  I notice that we can use weighted options in "Angular Segment Analysis" toolbox. However I only would like to calculate topological&metric step depth for certain selected segments with some WEIGHT. 

I can I realize that?

Thank you very much.
Linda

**Comment by varoudis** [comment]
not currently inside dX.
for step depth better use some GIS or Python
