### ISSUE TITLE
Visualising agents movement in 3D view

### ISSUE THREAD

**Issue by Qletesson** [varoudis/depthmapX#28]
Hi there, 

Whatever the plan I'm using I can't seem to get the 3D view to work. It had worked in previous versions of the software but it doesn't anymore. I might do something wrong but even with the tutorials, I cannot find a way to solve this issue. 

The agent analysis works perfectly fine (through analysis of the visual map and so on...) but not the 3D visualization and its related features such as dropping an agent, pausing its movement, etc. 

Any idea why this is ? 

Many thanks in advance, 

Quentin

**Comment by varoudis** [comment]
https://github.com/SpaceGroupUCL/depthmapX/issues

If this is still relevant please post on the link above. we have gathered most of them there.
Thanks
