### ISSUE TITLE
Exporting selected pixels 

### ISSUE THREAD

**Issue by zapador414** [varoudis/depthmapX#29]
Hi!

I have a question about exporting data. If I select an amount of pixels in the Map View , and then go to the table window, i can see that the selected pixels are checked. Is there any chance to export just the data selected to a *.txt file ? 

Thanks a lot!

Lucas Vásquez
![exporting selected pixels](https://user-images.githubusercontent.com/13966345/29773068-1e2f67f4-8bd2-11e7-9429-1936389641d3.jpg)

**Comment by varoudis** [comment]
[https://github.com/SpaceGroupUCL/depthmapX/issues](https://github.com/SpaceGroupUCL/depthmapX/issues)

Better request this feature on the link above. we have gothered most of them there.
Thanks
